version: "3.8"

services:
  nginx:
    image: ${NGINX_REPO}:${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-data:/vol/static
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/htpasswd:/etc/nginx/.htpasswd
    networks:
      - mynetwork
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - mynetwork
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"

  client:
    image: ${CLIENT_REPO}:${CLIENT_VERSION}
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"
  api:
    image: ${API_REPO}:${API_VERSION}
    env_file:
      - ./config/envFiles/django/prod/.env
    command: ./docker-entrypoint-prod.sh
    volumes:
      - static-data:/usr/src/app/vol
    networks:
      - mynetwork
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"

  celery:
    image: ${API_REPO}:${API_VERSION}
    env_file:
      - ./config/envFiles/django/prod/.env
    volumes:
      - static-data:/usr/src/app/vol
    command: celery -A config worker -l info
    networks:
      - mynetwork
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"

  celery-beat:
    image: ${API_REPO}:${API_VERSION}
    env_file:
      - ./config/envFiles/django/prod/.env
    volumes:
      - static-data:/usr/src/app/vol
    command: celery -A config beat -l info
    networks:
      - mynetwork
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"

  celery-flower:
    image: ${API_REPO}:${API_VERSION}
    env_file:
      - ./config/envFiles/django/prod/.env
    volumes:
      - static-data:/usr/src/app/vol
    command: celery -A config flower --url_prefix=/flower --basic_auth=${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}
    networks:
      - mynetwork
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"

  channels:
    image: ${API_REPO}:${API_VERSION}
    env_file:
      - ./config/envFiles/django/prod/.env
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    networks:
      - mynetwork
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"

  db:
    image: postgres:13-alpine
    env_file:
      - ./config/envFiles/postgres/prod/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_backups:/db_backups
    networks:
      - mynetwork
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"
      

  redis:
    image: redis:7.0.4-alpine3.16
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - mynetwork
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.availability == "true"

networks:
  mynetwork:
    driver: overlay

volumes:
  pgdata:
  static-data:
